### ISSUE TITLE
Don't try to cache non-GET requests

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/sw-toolbox#10]

**Comment by addyosmani** [comment]
Is this the issue we can use to track:

> If you set only a default route in sw-toolbox it applies to ALL requests. Browser sync is sending a POST request which is being picked up by the networkFirst strategy. This would all be fine except that you can't put POST requests into the cache, so you get an unhandled error. I need to make sw-toolbox cleverer and not try to cache things that the spec disallows.

? (cc [this thread](https://github.com/PolymerElements/polymer-starter-kit/pull/24) just in case)

**Comment by wibblymat** [comment]
Yes! Will update other thread.
