### ISSUE TITLE
Travis CI build broken

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#106]
As per https://travis-ci.org/GoogleChrome/sw-toolbox/builds/119568124:

```sh
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install google-chrome-stable google-chrome-beta
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 google-chrome-beta : Depends: libstdc++6 (>= 4.8.0) but 4.6.3-1ubuntu5 is to be installed
                      Depends: lsb-base (>= 4.1) but 4.0-0ubuntu20.3 is to be installed
E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics
apt-get install failed
Your build has been stopped.
```

**Comment by gauntface** [comment]
I was hoping I could get a fix in before this was noticed.

Basically Chrome only has 64 bit builds. I have a fix for this in Propel by using .deb pkgs instead and have a PR in for travis to fix the issue.

Will fix this with a PR next.

**Comment by gauntface** [comment]
Slightly less broken: https://github.com/GoogleChrome/sw-toolbox/pull/107

**Comment by gauntface** [comment]
This is fixed now: https://travis-ci.org/GoogleChrome/sw-toolbox/builds/119653829

Please reopen if you spot any issues.

**Comment by bstn362436** [comment]
Thank you for the fix

On Wednesday, March 30, 2016, Matthew Gaunt <notifications@github.com>
wrote:

> I was hoping I could get a fix in before this was noticed.
>
> Basically Chrome only has 64 bit builds. I have a fix for this in Propel
> by using .deb pkgs instead and have a PR in for travis to fix the issue.
>
> Will fix this with a PR next.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/sw-toolbox/issues/106#issuecomment-203519153>
>


-- 
Sent from Gmail Mobile
