### ISSUE TITLE
HTTP requests changing to HTTPS before hitting SW

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-toolbox#108]
Just noticed a difference between Chrome and Firefox Nightly (v47).

Making a fetch request over HTTP in Chrome is hitting the service worker with that URL. In Firefox however, the URL has it's protocol changed to HTTPS.

@jakearchibald @wanderview @slightlyoff I call on your mega brains for thoughts / insights.

I'm guessing that this is a HTST header issue perhaps as I noticed it when using http://developers.google.com.

**Comment by wanderview** [comment]
We explicitly test for this behavior:

  https://dxr.mozilla.org/mozilla-central/source/dom/workers/test/serviceworkers/test_hsts_upgrade_intercept.html

Also, I think the spec calls for the upgrade to take place before interception.  The upgrade takes place in step 4 of Main Fetch, but service worker intercept doesn't happen until later at step 3 of HTTP Fetch.

**Comment by gauntface** [comment]
Awesome, will double check spec and if that's a case put together a test case for a Chrome issue.

(Also now realising I completely messed up jake's and alex's github usernames)

**Comment by gauntface** [comment]
This looks like a Chrome bug, raised it here - https://bugs.chromium.org/p/chromium/issues/detail?id=599406
