### ISSUE TITLE
Offline and Lie-Fi (help please)

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/sw-toolbox#109]
Have the following code:

```javascript
global.toolbox.router.get('/(.*)', function(request, values, options) { 
  // networkFirst will attempt to return a response from the network,
  // then attempt to return a response from the cache.
  return global.toolbox.fastest(request, values, options).catch(function(error) {
    // If both the network and the cache fail, then .catch() will be triggered,
    // and we get a chance to respond with our cached fallback page.
    // This would ideally check event.request.mode === 'navigate', but that isn't supported in
    // Chrome as of M48. See https://fetch.spec.whatwg.org/#concept-request-mode
    if (request.method === 'GET' && request.headers.get('accept').includes('text/html')) {
      return toolbox.cacheOnly(new Request('offline-page'), values, options);
    }
    throw error;
  });
});
```
Having problems trying to add this to the above code: `{networkTimeoutSeconds: 3}`

Hope someone can help me, thanks.

@jakearchibald @wanderview @slightlyoff

**Comment by wibblymat** [comment]
First, I edited your post slightly for formatting, sorry about that.

Options like `networkTimeoutSeconds` are passed as a third parameter to the router methods like `toolbox.router.get`. So you would do:

```
toolbox.router.get(myPattern, myHandler, {networkTimeoutSeconds: 3});
```

Or, in the full example (but with comments removed for clarity):

```
global.toolbox.router.get('/(.*)', function(request, values, options) { 
  return global.toolbox.fastest(request, values, options).catch(function(error) {
    if (request.method === 'GET' && request.headers.get('accept').includes('text/html')) {
      return toolbox.cacheOnly(new Request('offline-page'), values, options);
    }
    throw error;
  });
}, {networkTimeoutSeconds: 3});
```

Your code already handles propagating the options between handlers.

**Comment by ayumihamsaki** [comment]
No need to say sorry, I have just started using github and need to learn how to format things better, thank you for fixing my comment and also for your comment. I was putting the networkTimeoutSeconds inside the code just like you said, I didn't click to think you had to put it at the end. Many thanks!
