### ISSUE TITLE
Browser compatiblity

### ISSUE THREAD

**Issue by iiison** [GoogleChrome/sw-toolbox#113]
Is it compatible with low level browsers too?

**Comment by NekR** [comment]
If you mean with old versions of browsers, then no, 

Any SW library requires ServiceWorker. You can look at a compatibility-table here (in the end of the page) https://developer.mozilla.org/ru/docs/Web/API/Service_Worker_API to find which versions of browsers support ServiceWorker.

**Comment by gauntface** [comment]
@NekR is right. Another take on service worker support is https://jakearchibald.github.io/isserviceworkerready/ which also includes general browser vendor opinions of SW.

Worth noting that service workers can be treated as a progressive enhancement (i.e. your page will work without service workers, it just won't work offline or make use of the cache.
