### ISSUE TITLE
Move documentation from README

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/sw-toolbox#118]
Currently it is easy to miss the API documentation in the README. While it is a huge chunk of content, it also isn't exactly clear that is the docs either.

We should move the API docs under a `doc` folder and cross-link that. Further we may want to take the usage section and move that under a `usage.md` file of the docs. This way the README is more precise to inform people about how the project helps them, how to include it, and what the license is.

I am going to try and have a PR made this afternoon to address this. It is critical that the documentation is very easy to find and scan over without the other content getting in the way.

**Comment by addyosmani** [comment]
SGTM

**Comment by gauntface** [comment]
+1 this.

Can follow a similar pattern to Propel which has a `doc-pages` section for pages like usage etc and then set up travis and publish script to deploy and version like: http://googlechrome.github.io/Propel/

Thoughts?

**Comment by Garbee** [comment]
I like the idea of auto-gen into gh-pages. Just didn't want to bring that up right now because of the rush to I/O everyone is in.

**Comment by gauntface** [comment]
I've been trying to script the hell out of it so it's trivial. Will do a PR and tag you in it - why addy closed this I am unsure - bad @addyosmani ?

**Comment by Garbee** [comment]
No, he accepted my PR which "fixed" this issue so it auto-closed.

**Comment by Garbee** [comment]
Also I just built [this project skeleton](https://github.com/Garbee/project-skeleton) to help prevent this in the future if one can remember to use it. It is just the initial setup and outline of different files with some guidance on what to include and where. This should help prevent README stuffing.
