### ISSUE TITLE
some incorrect doc URLs in README

### ISSUE THREAD

**Issue by psimyn** [GoogleChrome/sw-toolbox#121]
I think just these 3 need to be changed to:

```
[expressive approach](doc-pages/api.md#toolboxrouterheadurlpattern-handler-options) 
[usage](doc-pages/usage.md) 
[api](doc-pages/api.md)
```

**Comment by ragingwind** [comment]
For now, README still have incorrect urls of above docs

**Comment by gauntface** [comment]
Please feel free to open new issues when you find something currently broken to ensure we see this. I've just raised a PR that should fix this.
