### ISSUE TITLE
How do I get rid of the dinosaur?

### ISSUE THREAD

**Issue by tusharmath** [GoogleChrome/sw-toolbox#122]
I have set `precache` for each and every url that I need for my PWD to work.  I have also set the following caching policy —

```javascript
  toolbox.router.get('/(.*)', toolbox.cacheFirst)
```

Even after all this, when I put my phone in airplane mode I see the dinosaur :( 
Is there something else that one needs to do to make it work offline?

**Comment by gauntface** [comment]
Do you have an example we can look at?

**Comment by tusharmath** [comment]
@gauntface My code isn't hosted publicly. If you could ask for some really specific thing then I should be able to share.

**Comment by tusharmath** [comment]
I used the chrome debugger to figure out the issue and finally resolved it. Apparently I was not on HTTPS as I was using a local deployment setup.
