### ISSUE TITLE
Current Firefox (46) cannot update broken SW

### ISSUE THREAD

**Issue by NekR** [GoogleChrome/sw-toolbox#127]
See this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1267733
Basically, if SW is broken and throws an error for navigation request, request's document is never loaded and nothing can tell to Firefox to update SW.

Should we disable support SW for all Firefox version which do not have fix for that? I opinion is -- yes.

/cc @jakearchibald @addyosmani @wanderview 

I think I am going disable it in `offline-plugin` :-(

**UPD:** hmm.. probably wrong repo and this issue has to be created in `sw-precache`. Always confused by these names.

**Comment by NekR** [comment]
By disable I mean serving noop SW to it or just return early from every function for affected versions.

**Comment by gauntface** [comment]
I think it would make more sense for the developer to block on Firefox version and no register the service worker rather than the library block use of a browser.

Maybe this could be a recipe sample code + issues pointing out why you might want to do it.

**Comment by NekR** [comment]
I keep forgetting that you do not handle SW registration for users, but I do in `offline-plugin` so this is why I was concerned and thought about disabling it. Anyway, any library which wants to be _"jQuery for SW"_  (not `sw-*` or `offline-plugin` I suppose) should handle this case.

Closing then?

**Comment by gauntface** [comment]
Yeah sounds reasonable to me.
