### ISSUE TITLE
SW-Toolbox Future updates Suggestion

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/sw-toolbox#133]
Hi,

I am just wondering if Google has any plans to expand sw-toolbox and merge these five things to form a single complete package lib, either into sw-toolbox or create a new lib like sw-messaging.
1. Push API
2. Noficiation API
3. Background Synchronization API
4. Web Push Encryption API
5. GeoFencing API

And any other future api's for service worker...

**Comment by jeffposnick** [comment]
Those won't all make it into `sw-toolbox`.

We're prototyping an approach to Background Sync at https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-background-sync-queue

Our team's library for push messaging + notifications is https://firebase.google.com/docs/cloud-messaging/js/client
