### ISSUE TITLE
sw-Toolbox reports an empty precache when used with sw-precache

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-toolbox#135]
Since we advertise them as working together, this looks like a bug.

**Comment by jeffposnick** [comment]
Can you provide some additional information? What methods are you calling and what are they returning?

In general, the two libraries compliment each other, and the caches they maintain are independent.

**Comment by wibblymat** [comment]
I assume this about [this debug line](https://github.com/GoogleChrome/sw-toolbox/blob/master/lib/sw-toolbox.js#L63-64).

It's correct that Toolbox reports that it isn't precaching anything, because Precache is handling it.
