### ISSUE TITLE
Service worker runtime cache

### ISSUE THREAD

**Issue by acircuit** [GoogleChrome/sw-toolbox#141]
I am creating a progressive web app using service workers and i am using service worker toolbox to cache my content. Service worker code to cache my content :

Service worker code to cache my content :

toolbox.router.get('/(.)', toolbox.fastest);
toolbox.router.post('/(.)', toolbox.fastest);
toolbox.router.get('/(.)', toolbox.fastest, {origin: 'https://example.cloudfront.net'})
toolbox.router.get('/(.)', toolbox.fastest, {origin: 'https://example.in'})

The code is running fine as i am not seeing any error in the console. But how can i check whether the images from cloudfront or the url's configured above are getting cached and rendered from the cache itself.

**Comment by kuldeepkeshwar** [comment]
you can use chrome devtools .
Go to Network tab ,under the size column, you will see '(from ServiceWorker)' if a request being served by  the service worker.
To check if a resource is present in cache or not , go to Resouces tab ,under Cache Storage you can see all the request cached by sw.

**Comment by acircuit** [comment]
I am able to see the resources which need to be pre cahced. So , i will be able to see the files for runtime cache as well?

**Comment by spock123** [comment]
@acircuit  yes
