### ISSUE TITLE
Restore previous top-level sw-toolbox.js

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#143]
It broke `sw-precache`, as https://github.com/GoogleChrome/sw-precache/blob/master/lib/sw-precache.js#L184 depended on it existing.

When you do remove it, could it be as part of a major `sw-toolbox` semver release?

**Comment by wibblymat** [comment]
Yes, my bad. I didn't pay enough attention to the changes that @gauntface had made and didn't realise the output files had moved.

**Comment by wibblymat** [comment]
@gauntface since the build script is in `sw-testing-helpers` could you let us know if/how we can have the output be in `/` rather than `/build/`?

**Comment by addyosmani** [comment]
Ran into this with another project this evening. Mirror Jeff's comments about a major version if we're changing the path.

**Comment by justinfagnani** [comment]
So what should we do here, since we're completely broken on new installs because of this. Pin to an older version?

**Comment by jeffposnick** [comment]
`npm-shrinkwrap.json` with

```json
{
  "name": "sw-precache",
  "version": "3.2.0",
  "dependencies": {
    "sw-toolbox": {
      "version": "3.1.1"
    }
  }
}
```

Is a local workaround, but I'm very much hoping this can just be resolved with a 3.2.1 release of `sw-toolbox` that restores the file.

As far as I know, only @wibblymat has npm publishing permission for `sw-toolbox`, and it sounds like only @gauntface knows about the current build system, so...

**Comment by gauntface** [comment]
Mat will publish a new version now.

As an FYI, if you check out the contents of the shell script that performs releases, it explains the npm scripts it uses to give projects control of what and how something is published.

https://github.com/GoogleChrome/sw-testing-helpers/blob/master/project/publish-release.sh

In this case 'npm run bundle' in sw-toolbox was the thing in control. If there is anything I can do to make this more obvious please let me know. It's hard to surface stuff from shell scripts up, so any suggestions would be good here.

**Comment by wibblymat** [comment]
Ok, v3.2.1 published - sorry everyone.

//cc @justinfagnani @zzarcon
