### ISSUE TITLE
Where is companion.js?

### ISSUE THREAD

**Issue by gertst** [GoogleChrome/sw-toolbox#157]
In the main readme there's this demo code: 
`<script src="/path/to/sw-toolbox/companion.js" data-service-worker="my-service-worker.js"></script>`
However, I can't find the file companion.js.
Is this depricated? If so, what's the new way of doing this?

**Comment by gertst** [comment]
I found it in an older project. Looks like the only code inside companion.js is this:
```

(function() {
  "use strict";
  var workerScript = document.currentScript.dataset.serviceWorker;

  if (workerScript && "serviceWorker" in navigator) {
    navigator.serviceWorker.register(workerScript);
  }
})();
```

And this also works as expected.

**Comment by jeffposnick** [comment]
FWIW, it's at https://github.com/GoogleChrome/sw-toolbox/blob/master/companion.js

**Comment by wibblymat** [comment]
It's no longer being shipped in releases, though.
