### ISSUE TITLE
Service worker must be placed in root directory to access all files

### ISSUE THREAD

**Issue by benjaminmcdonald** [GoogleChrome/sw-toolbox#158]
sw-toolbox should warm the user when the service worker is not in the root directory

**Comment by skainth** [comment]
You may include the service worker javascript file outside of root as well. Following are your options:
Define a custom route (like /sworker.js) which, when hit, will serve the actual service worker file from some folder.
Or use can set "Service-Worker-Allowed" to specify the allowed scopes like "/". This will allow your service worker to control all pages served from your domain.

Source: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by jeffposnick** [comment]
Yes, I don't think this is within the scope (pun intended...) of what `sw-toolbox` should warn about, due to the variety of different serving setups and workarounds for relaxing the scope that exist.
