### ISSUE TITLE
Request method 'POST' is unsupported ... sw-toolbox.js:20:43

### ISSUE THREAD

**Issue by ValueBC** [GoogleChrome/sw-toolbox#16]
I get this error running Polymer Starter Kit 1.0.1, with a fresh install on Mac.
```
Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at TypeError (native)
    at http://localhost:3000/sw-toolbox/sw-toolbox.js:20:430
```

**Comment by SilverPaladin** [comment]
In Windows 7, using Polymer Starter Kit 1.0.0 and 1.0.1

    Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at TypeError (native)
    at http://localhost:3000/bower_components/sw-toolbox/sw-toolbox.js:20:430'

**Comment by curtiscovington** [comment]
Same issue, with sw-toolbox on 2.0.3.

**Comment by addyosmani** [comment]
This should be fixed in https://github.com/PolymerElements/polymer-starter-kit/blob/master (master) as it now pulls in the latest sw-toolbox + platinum-sw using the fix that landed for this.

**Comment by jgatjens** [comment]
:+1: Thanks !
