### ISSUE TITLE
Feature request: support multiple instances

### ISSUE THREAD

**Issue by wheresrhys** [GoogleChrome/sw-toolbox#160]
Say I want to use service worker to cache fonts and api calls. My ttl and versions for fonts are generally going to be unrelated to those for my api. With sw-toolbox it appears to be impossible to address this use case. However if I were able to create multiple sw-toolbox instances then I could configure each of them to behave exactly as I need.

**Comment by wibblymat** [comment]
I'm not really sure why you can't do this with toolbox as-is.

Why wouldn't this work for you?

```
const FONT_OPTIONS = {cache: {name: 'font-cache', networkTimeoutSeconds: 5}};
const API_OPTIONS = {cache: {name: 'api-cache', networkTimeoutSeconds: 25}};

toolbox.router.get(/^https:\/\/fonts.googleapis.com\//, toolbox.fastest, FONT_OPTIONS);
toolbox.router.get('/api/(.*)', toolbox.networkFirst, API_OPTIONS);
```

**Comment by wheresrhys** [comment]
I didn't realise that was possible, and it looks workable. (as a bit of feedback, h2 & h3 in the docs are styled the same, so I missed that all the `cache` settings are part of the options object)

**Comment by wheresrhys** [comment]
One problem with your approach is that `toolbox.precache` doesn't accept cache options. Would a PR to implement that be acceptable, or is there some reason it's not workable?
