### ISSUE TITLE
Is source map working properly?

### ISSUE THREAD

**Issue by jongmoon** [GoogleChrome/sw-toolbox#169]
Hello, 

I came to know this great tool for service worker. I've learned many thing by this tool. Thank you. :)
But I get to have question while using it.

For debugging I have used source-map that was built. 

First I had a problem because of source map path in sw-toolbox.js
`//# sourceMappingURL=./build/sw-toolbox.map.json`
But It's not big problem to me. I can be solved by remove `build`.
`//# sourceMappingURL=./sw-toolbox.map.json`

But my big problem is **"I could not take a break point" although its source tree appears on dev tools.**

![image](https://cloud.githubusercontent.com/assets/3255471/17467222/d6701602-5d56-11e6-806e-4a45573f521e.png)

I've tried to make break point on `Router.prototype.matchMethod` function (router.js) but the break point is made on fastest.js(53). Some breakpoints are made well. but most of all are not made on proper code.

So I tried another way of making source map by modifying gulpfile. 

I referenced this
https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

```js
 var bundler = browserify({
    entries: ['./lib/sw-toolbox.js'],
    standalone: 'toolbox',
    debug: true
  });
  var bundle = function() {
    return bundler
      .bundle()
      .pipe(source('sw-toolbox.js'))
      .pipe(buffer())
      .pipe(sourcemaps.init({loadMaps: true}))
      .pipe(uglify())
        // Add transformation tasks to the pipeline here.
      .pipe(sourcemaps.write('./'))
      .pipe(gulp.dest('./build/'));
  };
  return bundle();
```

It works very well.

What was my problem? How can I use source-map by not modifying gulf file. 
Thank you for your help in advance.

**Comment by wibblymat** [comment]
Yep, seems like out source map is not working properly. Sorry about that! We'll take a look.

**Comment by jongmoon** [comment]
@wibblymat Thank you! 👍
