### ISSUE TITLE
Default route doesn't check request protocol, picks up chrome-extension://

### ISSUE THREAD

**Issue by JohnPhilipPearson** [GoogleChrome/sw-toolbox#171]
error with extensions 

Example given during NYC Roadshow

sw-toolbox.js:18 Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported(…)(anonymous function) @ sw-toolbox.js:18

**Comment by mojim** [comment]
i have this problem too

**Comment by jeffposnick** [comment]
My guess is that this is related to default routes, as the logic currently [looks like](https://github.com/GoogleChrome/sw-toolbox/blob/master/lib/sw-toolbox.js#L86):

```js
if (handler) {
  event.respondWith(handler(event.request));
} else if (router.default && event.request.method === 'GET') {
  event.respondWith(router.default(event.request));
}
```

That `else if` clause should probably check the protocol of `event.request` to confirm that it's `https:` as an additional condition.

@JohnPhilipPearson, can you confirm that you're using a default route?

**Comment by JohnPhilipPearson** [comment]
That was the case

**Comment by JohnPhilipPearson** [comment]
That was the case using a default route

**Comment by Splaktar** [comment]
What effect does this exception have other than an error in the console? Does this break caching or anything else? Or is this completely harmless?

Asking, since we are seeing it on our conference site and having a lot of SW related problems. Additionally asking since this isn't in a usable bower release yet.

**Comment by jeffposnick** [comment]
The fix just went out with the [`3.4.0` release](https://github.com/GoogleChrome/sw-toolbox/releases/tag/v3.4.0).

I'd recommend upgrading if you have users with specific Chrome extensions installed and have bumped up against this bug. It's unlikely that it's caused extensive service worker-related issues, though, so please let us know (along with steps for reproductions, in a new issue) if you're seeing unexpected behavior.

**Comment by TimeBandit** [comment]
Say this today with a localhost server, went away when I opened the page in incognito mode. The chrome extension causing it is the 'Stayfocused' extension.

**Comment by FAHAD-guma** [comment]
const cacheName = 'v1';


// Call Install Event
self.addEventListener('install', e =>{
	console.log('Service Worker: Installed');

});

// Call Activate Event
self.addEventListener('activate', e =>{
	console.log('Service Worker: Activated');
	//Remove unwanted caches
	e.waitUntil(
	caches.keys().then(cacheNames => {
		return Promise.all(
		cacheNames.map(cache => {
			if(cache !== cacheName){
				console.log('Sercice Worker: Clearing Old Cache');
				return caches.delete(cache);
			}
		})
		)
	})
	);
});

//event.request.headers.delete("x-chrome-uma-enabled");
//event.request.headers.delete("x-client-data");
//Call Fetch Event
self.addEventListener('fetch', e => {
	console.log('Service Worker: Fetching');
	e.respondWith(
		fetch(e.request)
		.then(res => {
			//Make copy/clone of response
			const resClone = res.clone();
			//Open cache
			caches
			.open(cacheName)
			.then(cache => {
				//Add response to cache
				cache.put(e.request, resClone);
			});
			return res;
		}).catch(err => caches.match(e.request).then(res => res))
	);
});

thats my code and am getting similar error and its complaining line ---cache.put(e.request, resClone);---
Any help is highly welcom
