### ISSUE TITLE
Make successResponses more conservative?

### ISSUE THREAD

**Issue by samertm** [GoogleChrome/sw-toolbox#175]
I was bitten by options.successResponses accepting more values than I expected. Just from the name, I expected it to only cache 20x responses, but it also cache things that aren't really "successful" responses like 401s and 404s.

Would it make sense to change the default to be more conservative?

**Comment by jeffposnick** [comment]
There's some background at https://github.com/GoogleChrome/sw-toolbox/issues/75, which is still open. I'm going to close this issue in favor of that one, and feel free to way in there.
