### ISSUE TITLE
caching HTTPS request on localhost crashes browser

### ISSUE THREAD

**Issue by minaseem** [GoogleChrome/sw-toolbox#177]
On caching HTTPS request, browser crashes in development environment(i.e localhost). While it works fine in production since my application is on HTTPS.

**Comment by jeffposnick** [comment]
There shouldn't be anything inherent in `sw-toolbox` that could crash a browser.

If there's a bug in a browser's service worker implementation that causes a crash, and `sw-toolbox` happens to trigger that browser bug, the best approach is to follow up with the browser's official issue tracker with a full set of steps to reproduce the crash:

- [Chrome bug tracker](https://bugs.chromium.org/p/chromium/issues/list)
- [Firefox bug tracker](https://bugzilla.mozilla.org/)
