### ISSUE TITLE
Support for cache expiration

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#18]
Brainstorming a bit: it would be useful if `sw-toolbox` had built-in support for cache expiration. It might take the form of associating LRU or oldest-first expiration policies with a specific named `Cache` object, along with a maximum number of entries, and then enforcing those policies via the built-in methods that store new entries. IndexedDB could be used to aid in bookkeeping.

`sw-toolbox` currently makes some assumptions about there only being a single named cached that your app works with globally, so relaxing some of those assumptions might be part of this work.

**Comment by jeffposnick** [comment]
See also: https://twitter.com/marcosc/status/645740489669525504

Given that it's a common use case and the complications involved in everyone rolling their own solution, it seems like a good opportunity to solve it via `sw-toolbox`.

**Comment by NekR** [comment]
Sad that `event.request.headers`, otherwise it could be a good way to mark requests as temporary. But I am not even sure if SW caches stores all the headers for the request.
