### ISSUE TITLE
Use package.json's files field to cut down on what we publish

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#185]
We're currently distributing the following to `npm`:

```sh
$ ls
LICENSE			bower.json		docs			package.json		sw-toolbox.map.json
README.md		companion.js		lib			sw-toolbox.js
```

We should use the [`files`](https://docs.npmjs.com/files/package.json#files) field in `package.json` to limit what we publish.

Specifically, I don't think we need to publish the following:

- `docs/`
- `lib/`
- `bower.json`

**Comment by addyosmani** [comment]
I don't think we should distribute `docs` or `lib` as part of the package. Looking at the bower.json file, https://github.com/GoogleChrome/sw-toolbox/blob/master/bower.json#L4 seems like the only really useful hint and I don't think the lack of presence of this file is going to break anything. +1 for using `files`.

**Comment by jeffposnick** [comment]
`package.json`'s `main` field lists `lib/sw-toolbox.js`, so I guess we should continue to ship`lib/` as well. (It *might* be safe to just switch `main` to point to `build/sw-toolbox.js`, but we'd need to think more about how developers are consuming this library.)
