### ISSUE TITLE
how to creat a confg file that generate a servic worker that include sw-toolbox and sw-precache

### ISSUE THREAD

**Issue by alisorri** [GoogleChrome/sw-toolbox#190]

**Comment by alisorri** [comment]
i want the files in the cache update when i do changes in the same file in the server

**Comment by jeffposnick** [comment]
Do the following help?
- https://github.com/GoogleChrome/sw-precache/blob/master/sw-precache-and-sw-toolbox.md
- https://github.com/GoogleChrome/sw-precache/blob/master/GettingStarted.md#runtime-caching-for-dynamic-content

**Comment by jeffposnick** [comment]
Please reopen if that doesn't help.
