### ISSUE TITLE
Trying to load images from HTTP

### ISSUE THREAD

**Issue by aletorrado** [GoogleChrome/sw-toolbox#205]
Hi! I don't know if this is a `sw-toolbox` issue, but I'm trying to load passive insecure content such as images from HTTP, while using service workers in our HTTPS app.

This is mandatory for us because they're not managed by ourselves. Do you know why browsers are blocking such requests, and how can I force them to load, like a regular non-sw HTTPS page?

Thank you.

**Comment by jeffposnick** [comment]
Apologies, but as you suspect, this is not related to `sw-toolbox`.

The restrictions related to mixed content are imposed by the browser and follow the recommendations in the service worker specification. Any feedback about the current behavior is probably best conveyed via the service worker specification [issue tracker](https://github.com/w3c/ServiceWorker/issues).
