### ISSUE TITLE
Returning cached resource based on route without considering method

### ISSUE THREAD

**Issue by zmoshansky** [GoogleChrome/sw-toolbox#21]
I'm using sw-toolbox through Polymer's `platinum-sw-cache` and `iron-ajax` and it's come up with a bit of strange behaviour explained below:
```
GET /api/resource --> 200 {"data": [{"id": 1}, {"id":2}]
POST /api/resource --> Server sends 422 {"errors": [{"description": "can't be blank"}]}, SW intercepts and returns 200 {"data": [{"id": 1}, {"id":2}] `Status Code:200 OK (from ServiceWorker)`
```
However, When inspecting the service worker, it shows 2 Requests:
```
Request Method:OPTIONS
Status Code:200 OK
```
```
Request Method:POST
Status Code:422 Unprocessable Entity
```
and `POST https://localhost:4000/api/resource 422 (Unprocessable Entity)` in the console

TBH, I don't really expect anything but GET to be cached, which may the case, but it definitely shouldn't replace my POST's 422 and body with a 200 OK and the GET body.

**Comment by zmoshansky** [comment]
Upon digging more into the solution, it would seem that [cache.match](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match) shouldn't match the post request... :fearful: (since ignoreMethod defaults to false)

Chrome `43.0.2357.134 (Official Build) (64-bit)`

**Comment by wibblymat** [comment]
Hi @zmoshansky, I'm sorry I didn't see your issue earlier - apparently I unwatched the repo by mistake :/

Yes, this is a silly mistake on my part - the Response type should match the Request type. We already only cache GET requests, so I'll need to put a similar check around fetching from the cache.

Thanks for reporting!
