### ISSUE TITLE
Broken images "Dependency Status" and "devDependency Status" 

### ISSUE THREAD

**Issue by tobireif** [GoogleChrome/sw-toolbox#210]
![screenshot](https://cloud.githubusercontent.com/assets/80411/20960895/dadc046a-bc62-11e6-8292-a4667e3f34b3.png)

**Comment by jeffposnick** [comment]
It might have been a transient thing, or a bad image cache—they're showing up now.

![screen shot 2016-12-20 at 3 48 02 pm](https://cloud.githubusercontent.com/assets/1749548/21367350/d8d61f3e-c6cb-11e6-9c15-3b495a658321.png)

**Comment by tobireif** [comment]
Unfortunately they don't show up currently:

![screenshot](https://cloud.githubusercontent.com/assets/80411/21386184/eeb4dfa6-c771-11e6-98d4-c94a18215210.png)

I did a reload with disabled cache. Two images are 404.

**Comment by jeffposnick** [comment]
It's likely due to https://github.com/alanshaw/david-www/issues/357 in that case. I don't think there's any action on our end until that unreliability clears up. If the service remains unreliable, we may just ditch the badges entirely.
