### ISSUE TITLE
POST request not getting cached

### ISSUE THREAD

**Issue by chiragmongia** [GoogleChrome/sw-toolbox#218]
I want to cache a POST request for 5 minutes. My POST request entry looks like below-
```
toolbox.router.post(/myPostApi/, toolbox.cacheFirst, {
    cache: {
        name: 'myCache',
        maxAgeSeconds: 300
    }
});
```

This is not getting cached. The entries for GET requests in exact similar syntax are working fine.
Am I missing something?

**Comment by Garbee** [comment]
Ref: [W3C discussion](https://github.com/w3c/ServiceWorker/issues/693) on caching POST requests. Nothing in the toolbox is wrong, this  just isn't allowed by the current specification.

**Comment by Garbee** [comment]
I think the best course here is to clarify in our docs that anything beyond `GET` or `HEAD` (if web browsers support `HEAD`) is capable of being cached. As browsers only really support `POST` otherwise and they are incapable of being cached currently.

**Comment by chiragmongia** [comment]
@Garbee Thanks! The w3c service worker discussion makes a lot of sense.
