### ISSUE TITLE
Any workaround for wrong header on Openshift/rhcload

### ISSUE THREAD

**Issue by englishextra** [GoogleChrome/sw-toolbox#219]
```
Failed to register/update a ServiceWorker for scope ‘https://app-englishextra.rhcloud.com/’: Bad Content-Type of ‘application/octet-stream’ received for script ‘https://app-englishextra.rhcloud.com/serviceworker.js’.  Must be ‘text/javascript’, ‘application/x-javascript’, or ‘application/javascript’.
```
That's in Firefox

An in Chrome:
```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('application/octet-stream').

The script has an unsupported MIME type ('application/octet-stream'). https://app-englishextra.rhcloud.com/serviceworker.js
```
Yes, Openshift hosting (DIY cartridge) sends application/octet-stream for js files. 

Any   ideas?

**Comment by jeffposnick** [comment]
Sorry; this restriction comes from the [service worker specification](https://w3c.github.io/ServiceWorker/#update-algorithm), and is imposed by the browser. It's not something that `sw-toolbox` can control.

As per [step 7.7](https://w3c.github.io/ServiceWorker/#update-algorithm) of the update algorithm:

> Extract a MIME type from the response’s header list. If this MIME type (ignoring parameters) is not one of text/javascript, application/x-javascript, and application/javascript, then:
> 
> Invoke Reject Job Promise with job and a "SecurityError" exception.
> Asynchronously complete these steps with a network error.

**Comment by englishextra** [comment]
@jeffposnick Fair enough, thanks
