### ISSUE TITLE
Testing with LightHouse Shows I don't have SW registered and fails to respond with 

### ISSUE THREAD

**Issue by pmbanugo** [GoogleChrome/sw-toolbox#220]
I tested with Lighthouse on this site [https://shopping-list.now.sh/](https://shopping-list.now.sh/) and it says no service worker registered and it fails to return 200 when offline. If I test manually it shows that it installs a SW. I don't know if it's Lighthouse not detecting.

**Comment by jeffposnick** [comment]
I'm not seeing that:

![screen shot 2017-02-06 at 11 10 04 am](https://cloud.githubusercontent.com/assets/1749548/22655074/e8cac4ba-ec5c-11e6-82fe-879d821437d9.png)

If you continue to see issues, it's probably worth raising a bug against the Lighthouse project.

**Comment by pmbanugo** [comment]
Oops sorry I travelled and couldn't connect to the internet. Yeah I fixed what was causing it. I had some bad setup with requireJS which made the app take so long to load. Thanks!
