### ISSUE TITLE
Library request in CDNJS

### ISSUE THREAD

**Issue by extend1994** [GoogleChrome/sw-toolbox#230]
Hi,
I am a member of CDNJS.
There is a library request cdnjs/cdnjs#9843 on CDNJS and I want to know which files should be contained in the cdnjs that contains files running on browsers. Could you tell me that?
For more details, you can check CDNJS [README.md.](https://github.com/cdnjs/cdnjs/blob/master/README.md)
Thank you!

**Comment by jeffposnick** [comment]
Hello!

https://github.com/GoogleChrome/sw-toolbox/blob/master/sw-toolbox.js is the bundled runtime library. It contains code that runs within a service worker inside a browser.

**Comment by extend1994** [comment]
@jeffposnick 
Thanks for reply!
I have another question: There is no `sw-toolbox.js` under parent directory in some versions (such as 3.6.0 and 3.5.0). Instead, `sw-toolbox.js` is under `lib`. So my question is if the one under `lib` is what we need? Or we don't need to host any files in these versions (no `sw-toolbox.js` under parent directory)?

**Comment by jeffposnick** [comment]
That was an unfortunate bug—see #228 

You should expect a top-level `sw-toolbox.js` moving forward.

**Comment by extend1994** [comment]
@jeffposnick Thanks for reply!
Can you please tell me who should I fill out the `author` field in `package.json`?
Thank you again.

**Comment by jeffposnick** [comment]
You could use "Google's Web DevRel Team" as the author.

**Comment by extend1994** [comment]
Thank you! I will add the library ASAP.

**Comment by extend1994** [comment]
@jeffposnick Do you know if `shed.js` in v1.0.0 is a bundled file for a browser? Or there is (or not) another file for a browser? Sorry for bothering you again.

**Comment by jeffposnick** [comment]
No, `shed.js` is deprecated (it's the old name for this project) and shouldn't be something that's published.

**Comment by extend1994** [comment]
So we don't need v1.0.0 on our CDN, right? Another thing is that I found that there are only comment in https://github.com/GoogleChrome/sw-toolbox/blob/v3.6.1/sw-toolbox.js.

**Comment by jeffposnick** [comment]
You shouldn't host any version of`shed.js`.

Despite the formatting imposed by GitHub's pretty-printer, https://github.com/GoogleChrome/sw-toolbox/blob/v3.6.1/sw-toolbox.js contains actual code, not a single comment. You can paste it in to, e.g., http://jsbeautifier.org/ to confirm.

**Comment by extend1994** [comment]
OK Thanks a lot!
