### ISSUE TITLE
{{ project_root_url }} dead links on Github page

### ISSUE THREAD

**Issue by augbog** [GoogleChrome/sw-toolbox#231]
There are some dead links on the googlechrome.github.io/sw-toolbox homepage including the expressive approach link and the usage and api link at the bottom of the homepage.

I notice that they are using Jekyll's `{{ project_root_url }}` so not sure if this is jekyll specific but right now they 404.

**Comment by robdodson** [comment]
I also noticed the recipe link https://googlechrome.github.io/recipes/cache-expiration-options/ is a 404
