### ISSUE TITLE
cache lru

### ISSUE THREAD

**Issue by publicocean0** [GoogleChrome/sw-toolbox#253]
it is possible to define a lru policy or a way last request is always cached end eventually delete the oldest?
This will grant when cache works also when is full.

**Comment by jeffposnick** [comment]
Yes; for instance, using this [example configuration](https://googlechrome.github.io/sw-toolbox/recipes/cache-expiration-options/service-worker.js) from the docs:

```js
toolbox.router.get(/\.ytimg\.com\//, toolbox.cacheFirst, {
  // Use a dedicated cache for the responses, separate from the default cache.
  cache: {
    name: 'youtube-thumbnails',
    // Store up to 10 entries in that cache.
    maxEntries: 10,
    // Expire any entries that are older than 30 seconds.
    maxAgeSeconds: 30
  }
});
```

**Comment by publicocean0** [comment]
thanks it is very interesting. 
I explain my problem so you can understand better , maybe there is a solution here or maybe i can suggest a new feature here.
I have a stream of contents arriving by websocket. 
I want implement a cache so browser dont ask the same contents. 
Initially i developped a cache using filesystem api ... it is cool but now fsapi are deprecated and anyway not implemented by all browsers. So I have a problem. 
Considering the cache limit in appcache is higher than indexdb (a lot ) .... i thought to use it.
Content are arraybuffer. 
so if i save content as new Response(<array>) ... (maybe Response might permit also Stream of chunks)  might work simulating a new fetch request. 
Image i want listen a mp3 file. When downloaded user play it ... but i cant keep always it (as a blob) in memory because is not a static page ... it is a stream of contents.... To use blob for handling media for me is a very bad solution ... but all browser use. 
Do you think using your library i can implement my idea?

**Comment by jeffposnick** [comment]
I don't think that's something that `sw-toolbox` will help with, no. I don't want to say that it's impossible using the Cache Storage API, but there's nothing in `sw-toolbox` that is relevant to that scenario.

**Comment by publicocean0** [comment]
The problem there is nothing in html and web api rilevant for that scenario.
 i want suicide me :)
