### ISSUE TITLE
May I read package file for CACHE VERSION

### ISSUE THREAD

**Issue by mazipan** [GoogleChrome/sw-toolbox#257]
I add `var CACHE_VERSION = '-v1.0.0'` in my sw.js
But may I read this version from package.json ?

**Comment by gauntface** [comment]
I'm sorry, I dont understand your question or what you are trying to do.

**Comment by jeffposnick** [comment]
`sw-toolbox` is a library, with code that executes at runtime in the browser. You're not going to have access to your local `package.json` file in that context.

If you need to version caches or resources based on the context of your `package.json`, it sounds like you would be better served by using a library that integrates with your build process and generates an appropriate service worker file based on your local filesystem.

[`sw-precache`](https://github.com/GoogleChrome/sw-precache) is one such library that works alongside `sw-toolbox`, and a newer option is using [Workbox](https://workboxjs.org/) (which would fully replace `sw-toolbox`).
