### ISSUE TITLE
Allow for selection of more request properties like headers than just the URL

### ISSUE THREAD

**Issue by SGD1953** [GoogleChrome/sw-toolbox#268]
We would like to be able to cache a response for a given pattern but only in case a certain header is supplied (i.e. `CachableByServiceWorker: true`). Looking at the code it seems to be hard to achieve so I was wondering if there are any plans to support something like that (or if it is even desirable). Or if that use case is too specific if it would maybe make sense to add support for adding a callback to the options which would receive the request before it is getting cached & return `true/false` to indicate whether it should be cached or not? This would add a great deal of flexibility.

Thank you,
Danny

**Comment by jeffposnick** [comment]
It's not necessarily a common way of doing things, but it's certainly possible in `sw-toolbox` via something like:

```js
toolbox.router.get('/path/to/whatever', (request) => {
  if (request.headers.get('CachableByServiceWorker') === 'true') {
    // Network first will update the cache with the response when online,
    // and use the previously cached response when offline.
    return toolbox.networkFirst(request);
  }
  // Network only will avoid cache interaction.
  return toolbox.networkOnly(request);
});
```

This is something that's more straightforward in https://workboxjs.org, which offers a way of mixing in a [configuration plugin](https://workboxjs.org/reference-docs/latest/module-workbox-cacheable-response.CacheableResponse.html#main) to determine whether a response is cacheable into your normal routes.

**Comment by SGD1953** [comment]
Thank you @jeffposnick, very much appreciate the fast reply that even solved my problem!
