### ISSUE TITLE
Want to be able to use the Npmjs package as a Node library in builds

### ISSUE THREAD

**Issue by localnerve** [GoogleChrome/sw-toolbox#31]
First, thanks for this tool, it looks really great and promises to save tons of boilerplate.

I'm trying to use it as a component library in my own service worker build. I'm bundling the service worker instead of using importScripts for each module - Want one trip (no HTTP/2).

I'm using the sw-toolbox npm package 2.0.4, and I'm having difficulties:
  1. Uglify chokes on the pre-built source code.
  2. No 'main' in package.json, so require('sw-toolbox/sw-toolbox') is weird.

The raw error (Uglifying the built code):
```
WARNING in ./~/sw-toolbox/sw-toolbox.js
Critical dependencies:
17:438-445 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/sw-toolbox/sw-toolbox.js 17:438-445

ERROR in sw.84e0fb9382841b26f9da.min.js from UglifyJs
Unexpected token name «of», expected punc «;» [./~/sw-toolbox/sw-toolbox.js:50,0]
```

The npmjs package only has the pre-built source code, not the library code.
I know I can just use the git repo, but prefer npmjs and node package management semantics througout the project.

Any reason not to just publish the library source code in the npm package for a more "node aligned" experience?

**Comment by wibblymat** [comment]
Hi @localnerve!

The uglify error is the same as https://github.com/GoogleChrome/sw-toolbox/issues/28 - we're working on that.

As for no `main` in `package.json` and not including the rest of the files... yeah, you're right, those changes make sense.

I'll take a look.

**Comment by localnerve** [comment]
Probably worth mentioning, depending on the desired final packaging, the node package dependencies may not be correct (either) for this repo a node library.
For example, path-to-regexp and serviceworker-cache-polyfill are dependencies, not devDependencies.
