### ISSUE TITLE
Unable to match API requests

### ISSUE THREAD

**Issue by localnerve** [GoogleChrome/sw-toolbox#35]
I'm trying to match API requests that use cookie and qstring CSRF parameters.
I seem to be unable to match API requests in the cache.

I've verified the responses are getting into the cache, but I'm unable to match the key with subsequent requests.

Items of note:
1. Even though I specify { credentials: 'include' } in the Request, the Request that gets stored in the cache is { credentials: 'omit' }.
2. No way to send { ignoreSearch: true } to cache.match options.
3. vary: Accept-Encoding (Content-Encoding: gzip)

Example, CSRF tokens at end of url:
```
Key Url (Request in cache associated with response):
http://localhost:3000/_api/page;format=markdown;models=%5B%22LocalBusiness%22%2C%22SiteInfo%22%5D;pageTitle=About;resource=about;url=https%3A%2F%2Fapi.github.com%2Frepos%2Flocalnerve%2Fflux-react-example-data%2Fcontents%2Fpages%2Fabout.md?_csrf=DgDQBtRH-qbZvUXqBhAz6lsYwiE-JazMUjLs

Offline Url (Request made while offline, does not match):
http://localhost:3000/_api/page;format=markdown;models=%5B%22LocalBusiness%22%2C%22SiteInfo%22%5D;pageTitle=About;resource=about;url=https%3A%2F%2Fapi.github.com%2Frepos%2Flocalnerve%2Fflux-react-example-data%2Fcontents%2Fpages%2Fabout.md?_csrf=4Uq9fOBW-GYJRq-wjE_uaPjNW_QBlQutIp6I
```
I played around with my own version of sw-toolbox that added { ignoreSearch: true } in a specific case (for offline cache fallback), but did not get results.

I'm still looking for clear reason why I can't match the Request, but haven't found one just yet.
Ideas?

**Comment by jeffposnick** [comment]
`ignoreSearch` should give you the behavior you want, but is not currently implemented in Chrome :frowning:. https://code.google.com/p/chromium/issues/detail?id=426309 tracks the implementation.

What you can do in the meantime is write your own `sw-toolbox` request handler that normalizes the URL by stripping out the query parameters before it interacts with the cache. There's an example of implementing that sort of handler at https://github.com/googlecodelabs/polymer-offline-weather/blob/master/final/weather-fetch-handler.js (That project is using the `<platinum-sw>` Polymer wrapper to `sw-toolbox`, but the concepts are the same.)

Once you've defined your custom handler, you'd want to register it for anything requests that match your URL pattern via something like

```js
toolbox.router.get('/_api/page(.*)', myCustomHandler);
```

**Comment by localnerve** [comment]
Any update on `ignoreSearch` availability?

A growing amount of my code works around this.

It forces me to duplicate sw-toolbox strategies in my own code, where the principal difference is only that one request for the network is passed in, and a different request for the cache is used.

`ignoreSerarch` is sorely being missed by me.

**Comment by jeffposnick** [comment]
The [public bug](https://code.google.com/p/chromium/issues/detail?id=426309) is definitive when it comes to Chrome. I've been poking some folks about it, but there aren't any recent updates.

`CacheQueryOptions.ignoreSearch` is shipping in Firefox Nightly, for what that's worth.

**Comment by NekR** [comment]
I have made a `ignoreSearch` polyfill but nobody noticing ;-)

https://github.com/NekR/sw-cache-options
