### ISSUE TITLE
Rethink the pathname/origin split when defining handlers

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#38]
I've never taken to the [ExpressJS-style](http://expressjs.com/guide/routing.html) routes used to define custom handlers. It might make sense for situations in which you're normally matching same-origin URLs and you care about assigning portions of the pathname to request handler parameters, but I find it clumsy for, e.g., matching any request made against a given remote origin.

How about we start accepting a `RegExp` object as the first parameter to the `.get()`, etc. registration handlers? We could still support the old syntax as well. When there's a `RegExp` passed in, we use it as a match against the full `event.request.url` to determine whether the handler applies. We could expose any embedded capture groups in the parameters passed in to the handler, too.

That would allow for, e.g., 

```js
toolbox.router.get(/example\.com.+\.json/, function(request) {
  // handle GET request made to example.com that ends in '.json'
});
```

instead of the current

```js
toolbox.router.get('/(.*).json', function(request) {
  // handle GET request made to example.com that ends in '.json'
}, {origin: /example\.com/});
```

**Comment by localnerve** [comment]
In light of recent issues/comments here, I feel like I better speak up.

I think it is much nicer to have the origin separated than forcing people to fiddle around with building regexes/paths for different origins.

Example, set up precache and fetch for different CDN assets, where data.assets is an array of CDN assets collected at build time.

``` javascript
  toolbox.precache(
    data.assets
    .sort()
    .map(function (asset) {
      next = urlm.getHostname(asset);
      if (hostname !== next) {
        hostname = next;
        // New hostname, so install GET handler for that host
        toolbox.router.get('*', toolbox.networkFirst, {
          origin: hostname
        });
      }

      // Precache the asset in 'install'
      return new Request(asset, {
        mode: 'no-cors'
      });
    })
  );
```
