### ISSUE TITLE
Move build artefacts out of master

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/sw-toolbox#44]
The built version of the library (`sw-toolbox.js` and `sw-toolbox.map.json`) lives in the master branch, but in an ideal world we would only keep the source in the repo. It is easy for the built version to become out of sync with the source.

The only reason that we put the built version in git is because that's what Bower needs. However, we could create a separate `builds` branch, populate it only with the Bower version of the library, and tag new versions *there* instead. We can create a gulp task that automates this process for us when it is time to publish a new version.

The `npm` version would still come from master, but that doesn't need to be pre-built. If you are using `npm` then we can assume that you are going to `require()` the source files and do your own build.

Any concerns? @addyosmani @jeffposnick

**Comment by jeffposnick** [comment]
I'm not sure that `npm === I don't want a pre-built library`.

I like the idea of using `gulp` to automate publishing new releases, and I like the idea of moving the built library outside `master`. Presumably we could do both the GitHub tag and the `npm publish` as part of the same `release` task.

([Here's](https://github.com/GoogleChrome/sw-precache/blob/master/gulpfile.js#L32) what I'm doing for `sw-precache`, but that's simpler in that I'm publishing the source to `npm` as-is without doing anything to build them, and I'm [not tagging](https://github.com/GoogleChrome/sw-precache/releases) GitHub releases.)

**Comment by jeffposnick** [comment]
Somewhat relevant: http://nolanlawson.com/2015/10/19/the-struggles-of-publishing-a-javascript-library/

**Comment by gauntface** [comment]
Anyone against reusing the sw-testing-helpers publish script: https://github.com/GoogleChrome/sw-testing-helpers/blob/master/project/publish-release.sh

It's what I've configured for push-encryption-node: https://github.com/GoogleChrome/push-encryption-node/blob/master/package.json#L25

**Comment by wibblymat** [comment]
Done!
