### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by adityapunjani** [GoogleChrome/sw-toolbox#45]
Hi guys,

Could you publish the latest changes with a NPM release? Running into errors with 'options.cache.name' with the older version. 

Thanks

**Comment by jeffposnick** [comment]
@wibblymat, there are still a few more issues that I want to get to, but I don't think any of them will involve breaking changes like the cache options did. Do you want to tag and public a `3.0.0` release now, and we'll follow up with minor release increments?

@adityapunjani, if you want to play around with the current version prior to it being published officially, feel free to temporarily install it with `npm install https://github.com/GoogleChrome/sw-toolbox#master`

**Comment by wibblymat** [comment]
I finally released v3.0.0. And then immediately released v3.0.1 because I messed up the npm publish and you can't undo that any more :)

Sorry it took me so long

**Comment by adityapunjani** [comment]
Awesome, thanks! :)
