### ISSUE TITLE
Proposed recipe: fastest of cache vs network

### ISSUE THREAD

**Issue by dbialer** [GoogleChrome/sw-toolbox#48]
Much like cache and network race, https://jakearchibald.com/2014/offline-cookbook/#cache-network-race, so that an app can dual fetch (from cache and network, and if network loses, it will then cache the latest response for next time).

**Comment by jeffposnick** [comment]
That's already implemented as you describe in the quite useful [`toolbox.fastest`](https://github.com/GoogleChrome/sw-toolbox#toolboxfastest) request handler.

Please reopen if I'm misinterpreting your request and you're asking about something else.
