### ISSUE TITLE
API Feedback

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-toolbox#52]
Just reading through the readme and the naming of router.get, router.post, router.... generally doesn't really explain what the function is going to do when reading it on its own.

router.addGetRequestHandler <- much longer, but does explain the goal.
router.addGetHandler()

I was reading through the WSK implementation and it was my first time at reading through sw-toolbox code and was pretty quickly lost:

global.toolbox.router.get('/(.*)', global.toolbox.fastest, {
    origin: /\.(?:googleapis|gstatic)\.com$/
  });

**Comment by jeffposnick** [comment]
Related: https://github.com/GoogleChrome/sw-toolbox/issues/38 (The path/origin split always bugs me.)
