### ISSUE TITLE
Feature request: Update preFetch files

### ISSUE THREAD

**Issue by r-nathan** [GoogleChrome/sw-toolbox#57]
For the option global.toolbox.precache, it will be good to give an update strategy. Can we have a method or option to update the list of values in precache or take an array and update the cache with latest values.

**Comment by wibblymat** [comment]
Good idea, would definitely like to add something like this. The install/activate logic in `sw-toolbox` is not very flexible at the moment, so it's actually hard to work around it in your own code, even.

**Comment by r-nathan** [comment]
@wibblymat Any help?

**Comment by wibblymat** [comment]
Hi @r-nathan, we don't have a short-term plan for how to make bulk updating items easier. We are reviewing the whole API to try and find a sensible set of updates to make all in one go. This use case will be kept in mind while we do, but I wouldn't expect to see anything until next year.

If you want to manually override a cache entry, you can do it, though.

```javascript

caches.open(toolbox.options.cache.name).then(function(cache) {
  cache.add(myResourceURL);
});
```

That will add the resource to the cache, overwriting an existing item if it exists.

**Comment by r-nathan** [comment]
@wibblymat  Thank you. I will try the manual override option.

**Comment by jeffposnick** [comment]
I am closing this, as the safe/recommended approach would be to use [`sw-precache`](https://github.com/GoogleChrome/sw-precache) to keep local static assets fresh. Adding in similar functionality directly into `sw-toolbox` is outside of the plans for this project.
