### ISSUE TITLE
How to check if my cache exist

### ISSUE THREAD

**Issue by barakucrut** [GoogleChrome/sw-toolbox#59]
First , thanks for your great work to making this usefull helper.

just want to ask , how to check if my cache exist , 
ex: i have url https://test.com/api/getarticle?id=1

how to i know if this cache already store  in memory :)

many thanks for your help :)

**Comment by jeffposnick** [comment]
Service workers use the [Cache Storage API](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) to store `Request`/`Response` pairs. One of the nice things about this API is that it's also available via the context of a "normal" web page, as `window.caches`. So you can use code along the lines of

```js
if (window.caches) {
  window.caches.match('https://test.com/api/getarticle?id=1').then(response => {
    if (response) {
      // The URL is cached.
    } else {
      // The URL isn't cached.
    }
  });
} else {
  // The current browser doesn't support the Cache Storage API.
}
```

to asynchronously check whether a given URL is cached from the context of a web page.

**Comment by localnerve** [comment]
Just in case this question is about a development time need, please know in Chrome DevTools you can look at the Resources tab and view (and refresh) caches.
