### ISSUE TITLE
Option to define the scope when using the companion script

### ISSUE THREAD

**Issue by justmarkup** [GoogleChrome/sw-toolbox#62]
When using the companion script:

```
<script src="companion.js" data-service-worker="/sw.js"></script>
```

it would be great to have the option to define the scope with a data attribute, eg.

```
<script src="companion.js" data-service-worker="/sw.js" data-scope="/blog"></script>
```

What do you think?

**Comment by wibblymat** [comment]
I'm wary of adding stuff to the companion script. It's a really dumb script just to get people going, and I feel like you will be better off putting the relevant two lines into your own code the moment you need to do something non-default.

For reference, your case would only need:
```javascript
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js', {scope: '/blog'});
  }
```

somewhere in the JS of your site.

**Comment by justmarkup** [comment]
Thanks, I fully understand that you want to keep the companion script small.

**Comment by ayumihamsaki** [comment]
This is so great, I have been stuck for hours trying to make sw-toolbox work on my sub-domain. I replaced the companion.js file with the above script and now works error free. You should include that in a demo telling people to edit the companion.js file. Anyway thank you for that comment. Very happy now sw-toolbox working perfectly on all domains and sub-domains!

**Comment by jpmedley** [comment]
https://github.com/GoogleChrome/sw-toolbox/pull/105
