### ISSUE TITLE
Unit tests broken

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#63]
The current unit tests are broken for two reasons:

https://github.com/GoogleChrome/sw-toolbox/pull/39 made it so that the `default` route only applies to `GET` requests, and there are a number of tests that exercise the `default` route with other methods, starting at https://github.com/GoogleChrome/sw-toolbox/blob/master/tests/tests.js#L68 Those tests should probably just be removed.

Also, the tests wait on `.ready` instead of waiting until the page is controlled by the service worker, which makes the first test in the suite flaky. (See https://github.com/slightlyoff/ServiceWorker/issues/799).

**Comment by gauntface** [comment]
cc @jeffposnick @wibblymat 

I just took a look at the tests was wondering if you people would mind me doing PRs for the following:

- Is there a gulp task that starts up the server to run the tests? If not I'd like to add one
- I don't think the tests themselves should be precached - it seems a bit risky to me, I'd like to undo it: https://github.com/GoogleChrome/sw-toolbox/blob/master/tests/service-worker.js#L40 
- A number of tests are retuning the `respondOK`, is there a possibility that the routes could be mixed up internally? I'd probably change them to just return the route string.
- The caching test: https://github.com/GoogleChrome/sw-toolbox/blob/master/tests/tests.js#L84 is difficult to figure out what is the intended behaviour / it's testing multiple things in a single test. Would it make sense to write the tests to always start from fresh in terms of cache content and move to three tests:
    - Can't get not existant thing from cache
    - Get something that exists from cache installed in install step
    - Get something from cache that is added inside the test
    - Put something in the cache and delete it
    - Delete something that doesn't exist
    - Delete something defined in the install step

When I was playing with unit testing service workers I was completely unregistering and re-registering the test sericeworker(s) to ensure previous tests didn't impact the current tests. This is a bit over the top but it may allow for more robust tests if the test cases grow.

**Comment by jeffposnick** [comment]
Those changes all sound good to me!

Re: test automation, we've had https://github.com/GoogleChrome/sw-toolbox/issues/15 open for a while now, and I'd think that on the list of test-related tasks, that should probably be the highest. We missed broken tests for several months due to the lack of automation.

Getting a `gulp` task setup to run the tests automatically would be one part of that, but more challenging might end up being figuring out the CI setup, given the specific requirements (modern Chrome + Firefox).

**Comment by wibblymat** [comment]
@gauntface and I discussed CI in person. I suggested that he look at how Polymer elements interact with Travis and WCT. They actually `apt-get install google-chrome firefox` in the Travis set up then runt the tests against those 'local' browsers. Once we figure out exactly how they manage that we can copy it.

**Comment by jeffposnick** [comment]
It would be http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html, right? Have you asked @addyosmani about it too?
