### ISSUE TITLE
Proposal for precache API simplification

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-toolbox#77]
cc @addyosmani @wibblymat @jeffposnick 

At the moment the precache API allows strings, arrays and promises.

I would like to propose the following:

Change precache to accept only an array, this will cause:

    toolbox.precache('/single-asset);

to be written as:

    toolbox.precache(['/single-asset']);

Secondly remove support for nested arrays. This would require the developer to flatten the arrays and means the API wouldn't need to have some arbitrary limit on the number of nests.

     toolbox.precache(['/single-asset', ['/asset-nested', '/asset-nested-2']]);

becomes:

         toolbox.precache(['/single-asset', '/asset-nested', '/asset-nested-2']);

I don't feel like asking dev to do this is too much of an ask (lodash has a deepflatten method if consumers of the library wanted a quick solution).

I feel like the majority of users will want several assets cached rather than a single asset for the majority of the time.

I'm struggling what a good reasoning for promises in precache. I can see some value in being able to get an asset list, are there other use cases?

The main reason I see it as being beneficial is largely because the precache method abstracts away the ability to use event.waitUntil , so this support is your only option to perform some async action.

Ideally I'd like to see either precache take a single promise i this scenario and expect consumers of the library to make user of Promise.all or whatever means to manage logic required OR make it such that toolbox caching can be done from within the install step. 

For the single promise approach the expectation of this would be to return an array of strings to cache. This would ideally be named something differently to avoid overloading the precache method.

This would result in an API surface of something along the lines of:

toolbox.precache(<Array of Strings>);
toolboxprecacheAsync(<Promise which resolves to an array of strings>);

**Comment by jeffposnick** [comment]
Some background (not much context, but still) from the old repo: https://github.com/wibblymat/shed/issues/21

`<platinum-sw>` does make use of passing in a `Promise` to support the asset list use case: https://github.com/PolymerElements/platinum-sw/blob/master/bootstrap/sw-toolbox-setup.js#L25

I'm honestly not the biggest fan of the `toolbox.precache()` name, since it causes confusion with regards to `sw-precache`. I wouldn't object to a broader renaming.

**Comment by gauntface** [comment]
Happy for a broader renaming, not sure what a good alternative is though - precache describe the action of the method.

Regarding the seperation of calls, for or against @jeffposnick @wibblymat @addyosmani @jakearchibald?

toolbox.precache(<Array of Strings>);
toolboxprecacheAsync(<Single Promise>);

**Comment by jeffposnick** [comment]
There's already a `toolbox.cache()` method, which does the same thing as `toolbox.precache()`, except it can execute at any point, not just during the `install` event handler.

So... we *could* rename `toolbox.precache()` to `toolbox.cacheOnInstall()` (and I guess `toolbox.cacheOnInstallAsync()`).

**Comment by gauntface** [comment]
That sounds good to me. @wibblymat thoughts on this? I'm happy to have a crack at a PR

**Comment by gauntface** [comment]
@wibblymat feels the API is a good way to go (Discussed offline). Naming still uncertain.

**Comment by localnerve** [comment]
I would love to see this function (cacheOnInstall) moved into its own file/module so it can be reused as-is in a mock.

**Comment by gauntface** [comment]
I've simplified the precache() API to do take an array of strings or requests OR a promise that resolves to an array of strings or requests, which makes me think I can close this.
