### ISSUE TITLE
Question about examples.

### ISSUE THREAD

**Issue by fedex1** [GoogleChrome/sw-toolbox#8]
Hi @wibblymat Thanks for sw-toolbox!

I'm trying to find examples.  Can you point me to examples of applications using sw-toolbox.  I apologize for not finding them.

I tried from the documentation to create an example.  See https://civic-data.github.io/laws-of-planet-earth/us/ny/scripts_openlegislation/getdata1_swtoolkit.html

I only seem to be able to cache some of the data.

How do I turn on debug in the sw-toolbox.js?

It appears that globalOptions.debug and options.debug can be set to true, but I don't see how to set it.

Again I apologize for not finding it and thank you for the toolbox!

service worker support is amazing!  I agree with @jakearchibald  that this changes applications for the better!

**Comment by fedex1** [comment]
I think I made my little example work.  

See https://civic-data.github.io/laws-of-planet-earth/us/ny/scripts_openlegislation/getdata1_swtoolkit.html

One thing that would helpful in the Chrome Cache Storage interface would be to make the pagination of the cached items clearer.

I was wondering why the items seemed to not be cached if there were more than 50

It turns out you have to go to the next page :)

For anyone debugging, those little arrows are very important. :)

It would be helpful to have something like page 1 of 6 or something like that on the page.

![screen shot 2015-05-17 at 4 37 07 pm](https://cloud.githubusercontent.com/assets/167614/7672068/0e7410cc-fcb3-11e4-9b40-4f1693525e39.png)

**Comment by wibblymat** [comment]
Hi @fedex1!

There aren't any big examples available right now. This has been developed internally for projects at Google, and while some of them will be released as open source as some point, none of them has yet.

I should definitely make a proper demo and include it in the repo. I've opened #9 to track that.

You change global options like `toolbox.debug = true`. You set options on a per-method level using the options object like `toolbox.get('/', toolbox.fastest, { debug: true })`.

For suggestions about the developer tools experience, the team are always looking for things to improve. It would be awesome if you could submit feedback to at http://crbug.com/ though, as we tend to give more weight to requests that come from 'real' developers.

Please open/re-open an issue if you have more problems or feedback!

**Comment by fedex1** [comment]
Thanks and will do.

**Comment by briantq** [comment]
@wibblymat What sort of debugging should one see when setting toolbo.debug = true and passing debug:true when registering a runtimeCache?  I can't seem to get my runtimeCache working but I have to imagine it is because I'm doing something wrong and not that there's a bug with a basic use case.  I have been trying to get more information out of SW Toolbox but haven't figured out how.
