### ISSUE TITLE
How to cache another page with ajax

### ISSUE THREAD

**Issue by barakucrut** [GoogleChrome/sw-toolbox#85]
Hai every body , 

How i can cache another url with ajax request ,
this is my logic :
I have a list of article,when we on homepage "https://homepage.com" and click the detail article , i just change the content wrapper with ajax request ex : "https://homepage.com/tips/12" 
and when user go to offline mode and accsess this url  "https://homepage.com/tips/12" directly , they redirect to offline page because can't find the cache , except they accsess that page when they on online mode. And also redirect to /null

How to cache that's detail page without accsess direct page with ajax ?

this is my cache strategy :
toolbox.router.get('/tips/(.*)', toolbox.cacheFirst);

Thanks for your response guys :)

**Comment by gauntface** [comment]
The AJAX request will still go through the service worker and should cache the response. Are you still making a GET request to exactly the same url?

**Comment by jeffposnick** [comment]
When you're dealing with single-page apps that use client-side routing, there's usually a large number of unique URLs that all map back to the same HTML page. A setup like

```js
toolbox.router.get('/tips/(.*)', toolbox.cacheFirst);
```

is not going to give you the correct behavior for three reasons:

1. For "new" URLs that haven't previously been visited, there won't be a corresponding entry in the cache yet, and accessing those URLs while offline won't work (this is the issue you've reported).
2. Using a cache-first policy for any of those URLs means that once a user visits a page in a given browser, they'll continue to see the initially cached version of the page indefinitely, even after you push out updates to the underly HTML.
3. You'll end up fetching extra data from the network when there's an initial navigation to a new URL, and then storing duplicated HTML in your caches, which is wasteful. E.g. if a user previously made an initial navigation to `/tips/12` and then later on made another initial navigation to `/tips/13`, chances are the same underlying HTML "app shell" could have been reused for the second navigation request. What will end up happening instead is that two copies of the same HTML, each tied directly to the initial URL, will end up in your caches.

What we'd recommend doing for single-page apps is to embrace the "app shell" + dynamic content model. [This article](https://developers.google.com/web/updates/2015/11/app-shell) that @gauntface worked on is a great introduction, and if you'd prefer video content, [here's a talk I gave](https://www.youtube.com/watch?v=jCKZDTtUA2A) with a React-based example.

If you've structured your web app to use the app shell model, then what you can do is cache one copy of your shell HTML, and then instruct your service worker to use that cached copy for all navigation requests, regardless of whether it's a "new" URL or not. `sw-precache` is the right tool to use for caching and versioning your app shell, and the [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) option will take care of using that cached app shell HTML regardless of the request URL. You can see a fully configured example in the [app-shell-demo](https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo) directory.

`sw-toolbox` is best used to handle caching for the dynamic content that your app shell requests after it's loaded, e.g. an API call needed to populate a specific view.
