### ISSUE TITLE
Issue with caching 302 redirects

### ISSUE THREAD

**Issue by AaronLayton** [GoogleChrome/sw-toolbox#91]
I am not sure what the solution is here so posting to see if anyone else has any idea. I am using `toolbox.networkFirst`

I have a secure area
`/account/manage`
If the user tries to load that page we do a `Redirect("/account")` in MVC - this causes a 302 Found with the correct redirect.

from `/account` the user successfully logs in and then we do the same redirect to `/account/manage` but the original 302 is then being served from Service worker causing a loop back to `/account`. Surely this should be attempting the Network again and getting a correct 200 response?

If I change the URL in the address bar and load up `/account/manage` then the page loads correctly

 ```
const OWN_DOMAINS = ["localhost:53585"];

// Default cache rule
toolbox.router.get('/(.*)', function (request, values, options) {
    // networkFirst will attempt to return a response from the network,
    // then attempt to return a response from the cache.
    return toolbox.networkFirst(request, values, options).catch(function (error) {
        // If both the network and the cache fail, then `.catch()` will be triggered,
        // and we get a chance to respond with our cached fallback page.
        // This would ideally check event.request.mode === 'navigate', but that isn't supported in
        // Chrome as of M48. See https://fetch.spec.whatwg.org/#concept-request-mode
        if (request.method === 'GET' && request.headers.get('accept').includes('text/html')) {
            return toolbox.cacheOnly(new Request('/Offline'), values, options);
        }
        throw error;
    });
}, {
    cache: {
        maxEntries: 100,
        maxAgeSeconds: 86400
    },
    origin: ORIGIN_RULE
});
```

**Comment by AaronLayton** [comment]
Seems I am getting
`TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': Request with GET/HEAD method cannot have body.`

**Comment by wibblymat** [comment]
Hi @AaronLayton, thanks for reporting. I'll take a look.

As a workaround, the decision on which status codes should be cached is based on `toolbox.options. successResponses`, which is by default set to a Regex: `/^0|([123]\d\d)|(40[14567])|410$/`

302 matches the regex, so those will be cached. Overriding this value will let you tweak what happens.

**Comment by AaronLayton** [comment]
@wibblymat thanks I tried that also and it didn't seem to work. It was just tripping its self up because of the redirect I think.

Interestingly, I have tried it in Chrome Canary and I don't get the issue.

I am using this at the moment aswell
```
toolbox.router.get('/account*', toolbox.networkOnly, { origin: ORIGIN_RULE });
```

**Comment by gauntface** [comment]
I just tried to put together a super simple demo of this.

In Chrome it seems to work as you'd expect. Firefox has some issues. See: https://travis-ci.org/GoogleChrome/sw-toolbox/builds/111731164

Does this match the rough scenario you are performing? It's essentially a request for a url which redirects to a path that returns JSON but sets a cookie. The following request to the first URL then detects the cookie and returns a success piece of json.

https://github.com/GoogleChrome/sw-toolbox/blob/network-first/test/browser-tests/network-first/serviceworkers/redirects.js

The only thing I had to make sure of was that the cookies were being sent with the requests (this is largely due to the test set up - but may be application) - but perhaps the cookies will result in the cache not matching against the url?

Or is there something else that could be different?

**Comment by AaronLayton** [comment]
@gauntface I have a test server where you can see this happening if you like?
drop me an email - aaron.r.layton@gmail.com

It could end up being something I am doing, but without the service worker things seem to be OK

**Comment by ktmud** [comment]
Getting the same error here. It happens when a POST form submission returns 302 redirects. The error was thrown when trying to fetchAndCache the GET request we got redirected to.

**Comment by AaronLayton** [comment]
Yup that is what I am getting aswell - doesn't matter if I cache the response or use networkFirst - same thing happens. Although I was only getting it on Stable, if I tried this in Canary then it sempt to go through OK

**Comment by AaronLayton** [comment]
I still get this even if I have told sw-toolbox to do a networkOnly. Is this something wrong with fetch in general not being able to follow a redirect? @gauntface

**Comment by gauntface** [comment]
I think fetch at one point didn't follow redirects, but that was a while ago.

I added the test case for this but it sounds like I'm still not getting the right behavior. Can you give me a super cut down version of how to reproduce this? Just general instructions is fine (although an example snippet would be better ;) )

**Comment by ktmud** [comment]
This is a known issue of Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=573937
and was already fixed in the beta channel (tested with v50.0.2661.75).

**Comment by gauntface** [comment]
Thanks for the info @ktmud.

@AaronLayton if you get a chance to confirm this is fixed would love to know if your problem is resolved.

**Comment by AaronLayton** [comment]
I am not seeing this exact issue anymore - happy to close
