### ISSUE TITLE
Feature Request: Add bypass option for development

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-toolbox#92]
sw-precache has a method for basically indicating if the service worker should bypass the cache etc during development.

It would awesome to define some sort of option similar to this in sw-toolbox

```
 self.toolbox.options.bypasss = (location.origin === 'http://localhost');
```

I'm assuming this would just skip route matching in sw-toolbox and fallback to the network.

**Comment by barinali** [comment]
Just a note: we've `Bypass for network` option on Google Chrome's Developer Tools. At least we can use that option for this action.

**Comment by gauntface** [comment]
Yeah I think this was raised long before that feature was available.
