### ISSUE TITLE
API Updates

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/sw-toolbox#98]
Master issue to track the updates that I would like to make to the Toolbox API

- [ ] No longer automatically register event handlers
- [ ] Make the cache name easier to configure
- [ ] Simplify - regex vs. express-style is slightly confusing
- [ ] Add ability to 'refresh' a cache

**Comment by felquis** [comment]
Nice touch

It's kind related, shouldn't sw-toolbox delete old cache names automatically? Look this print 
![image](https://cloud.githubusercontent.com/assets/736728/14889725/539b1706-0d36-11e6-940f-cd99f8e0f2ed.png)

Changed from 7 to 7.1 but the version 7 still there, and if I update to 7.2, 7.3 etc.. all the old version still there too.

**Comment by wibblymat** [comment]
Only the cache that starts with `$$$toolbox-cache$$$...` is managed by toolbox. If you have specified your own caches to use with some of the helpers then you will have to manage those caches yourselves. We just don't have any way to know which caches are supposed to be there and which can be deleted, especially since caches are shared across the whole origin while a SW is limited to a scope.

**Comment by jeffposnick** [comment]
I'm going to argue that we should close this in favor of discussions like https://github.com/GoogleChrome/sw-helpers/issues/44
